version: "3"

networks:
  monitoring:
    driver: bridge

services:

  mobiles:
    build:
      context: ./microservices/mobiles  #building image of books micro-service
      dockerfile: Dockerfile
    container_name: mobiles-services
    ports:
      - 4545:4545 #change the port number to your chosen PORT number as per your .env file
    networks:
      - monitoring

  customers:
    build:
      context: ./microservices/customers  #building image of books micro-service
      dockerfile: Dockerfile
    container_name: customers-services
    ports:
      - 4550:4550 #change the port number to your chosen PORT number as per your .env file
    networks:
      - monitoring

  orders:
    build:
      context: ./microservices/orders  #building image of books micro-service
      dockerfile: Dockerfile
    container_name: orders-services
    ports:
      - 4555:4555 #change the port number to your chosen PORT number as per your .env file
    networks:
      - monitoring

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - 12345:12345
    volumes:
      - ./configs/config.alloy:/etc/alloy/config.alloy
      - ./alloy/data:/var/lib/alloy/data
    environment:
      - CONFIG_FILE_PATH=/etc/alloy/config.alloy
    networks:
      - monitoring
    depends_on:
      - mobiles
      - orders
      - customers
    

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "4318:4318"  # otlp http
      - "4317:4317" # otlp grpc
      - "14268:14268"  #jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo query      
    volumes:
      - ./configs/tempo-config.yaml:/etc/tempo/tempo.yaml
      - ./tempo-data:/tmp/tempo
    command: 
      - '--config.file=/etc/tempo/tempo.yaml'
    networks:
      - monitoring
    depends_on:
      - alloy
      - mobiles
      - orders
      - customers


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - .\configs\prometheus.yaml:/etc/prom/prometheus.yaml
    command: 
      - '--config.file=/etc/prom/prometheus.yaml'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
    ports:
      - 9090:9090
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/tmp:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - monitoring